apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: fh-swifty-chatbot
  name: fh-swifty-chatbot
  namespace: fh-swifty-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fh-swifty-chatbot
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        io.kompose.service: fh-swifty-chatbot
    spec:
      containers:
        - image: fh-swifty-chatbot
          name: fh-swifty-chatbot
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONVERSION
              value: "3.13"
            - name: LANGSMITH_TRACING
              value: "true"
            - name: LANGSMITH_ENDPOINT
              value: "https://api.smith.langchain.com"
            - name: LANGSMITH_PROJECT
              value: "fh-swifty-chatbot"
            - name: LANGSMITH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fh-swifty-chatbot-secrets
                  key: LANGSMITH_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: openai-api-key
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fh-swifty-chatbot-secrets
                  key: TAVILY_API_KEY
          resources:
            limits:
              memory: 2Gi
              cpu: 2000m
            requests:
              memory: 512Mi
              cpu: 500m
      restartPolicy: Always
      autoMountServiceAccountToken: false
status: {}
